# Generated by Django 3.2.19 on 2023-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=1000)),
            ],
        ),
    ]
